# Data Collection

## Imports

In [1]:
import kagglehub
import pandas as pd
import requests

## 1. AWS SaaS Sales Dataset (Kaggle)

In [3]:
# Download Dataset from Kaggle
path = kagglehub.dataset_download("nnthanh101/aws-saas-sales")

# Load into DataFrame
df_saas = pd.read_csv(f"{path}/SaaS-Sales.csv")

# Save raw data locally
df_saas.to_csv("../data/raw/saas_sales.csv", index=False)

df_saas.shape

Warning: Looks like you're using an outdated `kagglehub` version (installed: 0.3.13), please consider upgrading to the latest version (1.0.0).

(9994, 19)

## 2. World Bank - GDP per Capita
**Explanation:** World Bank API provides economical data for every country, no fees, no API key. 
We need 2 indicators (indicators):

  - NY.GDP.PCAP.CD = GDP per Capita in US-Dollar                                                                                                                                                                                                                      
  - IT.NET.USER.ZS = Internet-Users in % of the population

In [14]:
# Fetch GDP per capita (current US$) for all countries, most recent year
url_gdp = "https://api.worldbank.org/v2/country/all/indicator/NY.GDP.PCAP.CD?format=json&per_page=300&date=2020:2023&mrnev=1" 
response_gdp = requests.get(url_gdp)
data_gdp = response_gdp.json()[1]       # API provides Array with 2 elements: [0] = metadat, [1] = actual data

# Parse into DataFrame
df_gdp = pd.DataFrame([
    {"Country": item['country']['value'], "GDP_per_Capita": item['value']}
    for item in data_gdp if item['value'] is not None       # filter for countries with no data
])

df_gdp.to_csv("../data/raw/gdp_per_capita.csv", index=False)
df_gdp.shape

(262, 2)

## 3. World Bank - Internet Penetration

In [15]:
# Fetch internet users (% of population) for all countries, most recent year
url_net = "https://api.worldbank.org/v2/country/all/indicator/IT.NET.USER.ZS?format=json&per_page=300&date=2020:2023&mrnev=1"                                                                                                                                       
response_net = requests.get(url_net)                                                                                                                                                                                                                                
data_net = response_net.json()[1]

# Parse into DataFrame
df_net = pd.DataFrame([
    {"Country": item['country']['value'], "Internet_Penetration": item['value']}
    for item in data_net if item['value'] is not None
])

df_net.to_csv("../data/raw/internet_penetration.csv", index=False)
df_net.shape

# NOTE: same pattern, just different indicator; same procedure every time, get as much indicators as needed

(246, 2)

# 4. Check DataFrames

In [16]:
# AWS SaaS-Sales
df_saas.head()

,Row ID,Order ID,Order Date,Date Key,Contact Name,Country,City,Region,Subregion,Customer,Customer ID,Industry,Segment,Product,License,Sales,Quantity,Discount,Profit
0,1,EMEA-2022-152156,2022-11-09,20221109,Nathan Bell,Ireland,Dublin,EMEA,UKIR,Chevron,1017,Energy,SMB,Marketing Suite,16GRM07R1K,261.9600,2,0.00,41.9136
1,2,EMEA-2022-152156,2022-11-09,20221109,Nathan Bell,Ireland,Dublin,EMEA,UKIR,Chevron,1017,Energy,SMB,FinanceHub,QLIW57KZUV,731.9400,3,0.00,219.5820
2,3,AMER-2022-138688,2022-06-13,20220613,Deirdre Bailey,United States,New York City,AMER,NAMER,Phillips 66,1056,Energy,Strategic,FinanceHub,JI6BVL70HQ,14.6200,2,0.00,6.8714
3,4,EMEA-2021-108966,2021-10-11,20211011,Zoe Hodges,Germany,Stuttgart,EMEA,EU-WEST,Royal Dutch Shell,1031,Energy,SMB,ContactMatcher,DE9GJKGD44,957.5775,5,0.45,-383.0310
4,5,EMEA-2021-108966,2021-10-11,20211011,Zoe Hodges,Germany,Stuttgart,EMEA,EU-WEST,Royal Dutch Shell,1031,Energy,SMB,Marketing Suite - Gold,OIF7NY23WD,22.3680,2,0.20,2.5164

In [17]:
# GPD per Capita
df_gdp.head()

                          Country  GDP_per_Capita
0     Africa Eastern and Southern     1615.396356
1      Africa Western and Central     1411.337029
2                      Arab World     7583.811701
3          Caribbean small states    19903.811231
4  Central Europe and the Baltics    24604.806860

In [18]:
# Internet user all countries
df_net.head()

                                       Country  Internet_Penetration
0                  Africa Eastern and Southern                  30.4
1                   Africa Western and Central                  42.4
2                          East Asia & Pacific                  88.4
3  East Asia & Pacific (excluding high income)                  88.1
4   East Asia & Pacific (IDA & IBRD countries)                  88.9

In [ ]:
# check time intervall for sales
df_saas["Order Date"] = pd.to_datetime(df_saas["Order Date"])                                                                                                                                                                                                       
df_saas["Order Date"].dt.year.value_counts().sort_index()

Order Date
2020    1993
2021    2102
2022    2580
2023    3319
Name: count, dtype: int64

In [ ]:
# Check for european data
df_net[df_net["Country"].str.contains("Germany|France|United Kingdom", case=False)]

            Country  Internet_Penetration
100          France               88.6538
105         Germany               93.5000
234  United Kingdom               96.2988